# docker-compose.prod.yml
services:
  app:
    env_file:
      - .env.docker.production
    volumes:
      - ./:/var/www/html
      - ./.env.docker.production:/var/www/html/.env

  nginx:
    ports:
      - "172.17.0.1:8081:80"

  mysql:
    ports: []